// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package graphql

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("./schema", "root.graphql", "\"c2NhbGFyIERhdGVUaW1lCgpzY2hlbWEgewogICAgcXVlcnk6IFF1ZXJ5CiAgICBzdWJzY3JpcHRpb246IFN1YnNjcmlwdGlvbgogICAgbXV0YXRpb246IE11dGF0aW9uCn0KCnR5cGUgUXVlcnkgewogICAgZ2V0VXNlcihpZDogU3RyaW5nISk6IFVzZXIKfQoKdHlwZSBTdWJzY3JpcHRpb24gewogICAgdXNlcnM6IFVzZXIhCn0KCnR5cGUgTXV0YXRpb24gewogICAgY3JlYXRlVXNlcihmaXJzdE5hbWU6IFN0cmluZyEsIGxhc3ROYW1lOiBTdHJpbmchLCBlbWFpbDogU3RyaW5nKTogVXNlciEKfQo=\"")
	packr.PackJSONBytes("./schema", "users.graphql", "\"dHlwZSBVc2VyIHsKICAgICMgZGIgcmVzb2x2ZXJzCiAgICBpZDogU3RyaW5nIQogICAgZmlyc3ROYW1lOiBTdHJpbmchCiAgICBsYXN0TmFtZTogU3RyaW5nIQogICAgZW1haWw6IFN0cmluZwogICAgY3JlYXRlZEF0OiBEYXRlVGltZSEKCiAgICAjIG90aGVyIHJlc29sdmVycwogICAgZnVsbE5hbWU6IFN0cmluZyEKfQo=\"")
}
